language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script:
- coverage run -m unittest discover -s testing
after_success:
- coveralls
env:
  global:
  - secure: pwsDdiu5N4v/S2WVBTjy+oRqhfefvUs61m+oRIoxUHxNYhe2MRgOoafRjEVr5Vs3iTSzRZw/+VbeIerqpljt9oQUWHaWN6ZrOMmQmYqOSvqrV91kVr+u8j8n9fE5oc27bx+xropGa51aCM10A21fsmMX0WAsY9fi5ifU3L9Unwlih3A8+e2pCrBO53EXaPOBrNW/JwpX4WG9K7DZTL9dIdqHk9p6AsMrG55T6oVWOpVj2PXD+9tjdzPi9L1cjsLz+dv9IepsdVDq2Z6KtqJMERxKSmsX22m9zOXSTw2s2rHLf8xrSg6M4JSN5micM0LKNOW3N0SKJamKLvvIIfC9Um+Ii4ksZN3kt8dc8DZjE/9fACgXq2zk5TT+pPdZfDnakZMoyqL0dC38zUN/tB2pSzr8pccXRO83ZSysjyt8lGrviAnmP8bFKkfqMI+22OriPBx14ZGattdyrsolMO5Whvw5aCWY2lwhpXh9RtXy+6hTSaLkE8dE5Bs79M7uC4uhf6ipkdqYVZAeL8AMPTF64g6969IMp+nzjzrzXayvOdGCs58G4nUQtzSaQHIEf0pEnutg65Oxtf+6aZEyRV52zZ9D5oABss8pTbtB4tH5DhGnF0WyukKoaFiVOIeH3eSB/tQA6xqSGym05RVWvS4ej9ZwIR5pRVXmNeJ4wCcRZPE=
  - secure: qJnqqprKRwh1/Et80COnRpmSUDnOJ88DQXL78KTPonpTn3UUEfFb+dYmbX5N8roNfPX++IH1oU7Qq7KbGqH/Ll6tb4ImSoDKdpwoM/HUaM4vnh1GYDVAjtRTQ51ViyaxXO+tPl/NaRI/J3F0wIXeUisPqSeecY7gzhdyEAwAo29qTi7S4sKqHLeJ5RUnpeVQotseTZZ3ZNIz7Oaufy/EQ3hU/LX70xro33WtRoYoTvu7xZeDHCz8pn0TxkUkFJZhWapqHUst+ux5olGfndxZLqpfOCvIQ4s3wDRb0IdIVrB8vmkgv1JvT0B+S7nKC9Ve5H87NkQ58wyGstPRTFqiYNuIC7xrD9BxeXfkx0tx6UBYhjn4GuNvVD2kmesdGXUZ41QzO1SErTUbHENI4TdM3ycbRfNHSAExxxQtU0OUQvm2wJDeTnRCwokPJeipc1NOIp8XKxXAGlk/BRJiHhuW2dfxC6PpZB1veYQYQHGLoeJm4NIUymMY4ROpKywZzRwR/D70WexRVjvdn+ppY65DNWAPPw6+oUwAmd/+Iaqf8SwXNVi9fIuYDzRuWgpX7KPgXs7Sp29CNsXyK7QyVeGMpGO0tk2utsUVWa0taZrdXdsel3O3eP8L8wn2S/7zzNOG4i57gzugoiuRHte2k98Y7XpNZvIYkeUaRnLdOg+z5SY=
